name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run mkdir
        run: mkdir -p ./apt-repo/pool/main/
        
      - name: Run mkdir
        run: mkdir -p ./apt-repo/dists/stable/main/binary-amd64

      - name: Run build_pkg script
        run: bash build_pkg.sh
        
      - name: Run ls
        run: ls
        
      - name: Run cd main && ls
        run: cd apt-repo/pool/main/ && ls
        
      - name: Run cd binary-amd64 && ls
        run: cd apt-repo/dists/stable/main/binary-amd64 && ls
        
      - name: Run cd && scan packages
        run: cd apt-repo && dpkg-scanpackages --arch amd64 pool/ > dists/stable/main/binary-amd64/Packages
        
      - name: Run cd && ls
        run: cd apt-repo/dists/stable/main/binary-amd64 && ls
      
      - name: zip Packages
        run: gzip -9 apt-repo/dists/stable/main/binary-amd64/Packages 
     
      - name: Run cd && ls
        run: cd apt-repo/dists/stable/main/binary-amd64 && ls
        
      - name: Run cd && ls
        run: cd apt-repo/dists/stable/main/binary-amd64 && ls
        
      - name: Run cd && make Release
        run: cd apt-repo/dists/stable/ && ls
        
      - name: mv
        run: mv generate-release.sh apt-repo
        
      - name: generate release
        run: cd apt-repo && bash generate-release.sh > Release
        
      - name: Run cd && ls
        run: cd apt-repo && ls
        
        #cd ~/GIT/vova_repo/
#~/GIT/vova_repo/generate-release.sh > Release
        
        
        
        
        


