name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run mkdir
        run: |
          mkdir -p ./apt-repo/pool/main/
		  mkdir -p ./apt-repo/dists/stable/main/binary-amd64

      - name: Run build_pkg script
        run: bash build_pkg.sh


      - name: Run ls
        run: ls
